server.port=8080
spring.application.name=gateway-service
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.routes[0].id=catalogue-service
spring.cloud.gateway.routes[0].uri=lb://catalogue-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/produits/**
spring.cloud.gateway.routes[1].id=commande-service
spring.cloud.gateway.routes[1].uri=lb://commande-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/commandes/**
spring.cloud.gateway.routes[2].id=paiement-service
spring.cloud.gateway.routes[2].uri=lb://paiement-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/paiements/**
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
management.endpoints.web.exposure.include=*
