FROM eclipse-temurin:21-jdk AS build
# force rebuild 2026-03-16
WORKDIR /app
# Ajout du cache Maven
COPY .m2 /root/.m2
COPY .mvn .mvn
COPY mvnw .
RUN chmod +x mvnw
COPY pom.xml .
COPY src ./src
RUN ./mvnw package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
