server.port=8082
spring.application.name=commande-service
spring.datasource.url=jdbc:postgresql://commande-db:5432/commandedb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
management.endpoints.web.exposure.include=*
logging.level.com.example.commande_service=DEBUG
